ActivityWatch/docs

api-reference.rst, conf.py, installing-from-source.rst, rest.rst, rtd-requirements.txt
- Sphinx automodule calls were failing in `api-reference.rst`, this
was fixed by adding the necessary aw modules to
rtd-requirements.txt
- Unnecessary instruction to install of virtualenv was removed
=> Fixed autodoc of aw modules by requiring them

getting-started.rst
This better mimics the Unix like `~` usage for the others, removing the need for "variable replacement" by the user. Paths in this format are supported in a lot of places in Windows, such as File Explorer, the classic Run dialog, and traditional CMD.EXE. PowerShell users should already know how to convert these already, so not including that here. (For reference: `%USERPROFILE%` is supported as `~` in PowerShell, and `$env:LocalAppData` is the variable format for `%LocalAppData%`.)
=> Use environment variables in Windows paths

getting-started.rst
I downloaded activitywatch-v0.8.3-linux-x86_64.zip and to use the `start.sh` script I had to adjust as in this commit
=> fix start.sh script

getting-started.rst
You might want to make ``aw-qt`` start automatically on login using the: deleted "using the"  (Some hints might still be useful for lay folks like me.)
=> docs: fixed incomplete sentence in getting-started.rst

watchers.rst
I just built a watcher package for Atom code editor. Would you include it in your list?
https://github.com/NicoWeio/aw-watcher-atom
https://atom.io/packages/aw-watcher-atom
=> Add NicoWeio/aw-watcher-atom to list of code editor watchers

getting-started.rst
I'm not sure I'm adding the right locations for aw-qt autostart.  But in any case this sentence was unfinished.
=> docs: updated autostart section in getting started guide

src/installing-from-source.rst
I was curious about this project and decided I wanted to build it from the source.
I followed all the instructions but the ` make install ` failed :
```
(venv) ➜  activitywatch git:(master) make build
if [ -e "aw-core/.git" ]; then \
echo "Submodules seem to already be initialized, continuing..."; \
else \
git submodule update --init --recursive; \
fi
Submodules seem to already be initialized, continuing...
make --directory=aw-core build
make[1]: Entering directory '/home/riha/dev/garage/activitywatch/aw-core'
poetry install
make[1]: poetry: Command not found
make[1]: *** [Makefile:4: build] Error 127
make[1]: Leaving directory '/home/riha/dev/garage/activitywatch/aw-core'
make: *** [Makefile:29: build] Error 2
```
I realized I needed to have **Poetry** installed.
After installing Poetry, …
=> docs: Adding an item in the dependency list of installing-from-source.rst

src/installing-from-source.rst
* with 3.8 it errors because of sip
* related issue: https://github.com/ActivityWatch/activitywatch/issues/433
=> docs: when building, Python should be 3.6 or 3.7

.github/workflows/docs.yml
How about uploading build artifacts as in [aw-webui](https://github.com/ActivityWatch/aw-webui/commit/ba2374bdf7c580412837022432d41404b4332d1d)?
Edit: As my proposed updated workflow already ran on this PR, I can report that the size of the upload is 7 megabytes.
=> CI: upload build directory as artifact

src/features/categorization.rst
`^` in RegEx should be for matching the start, not end
=> Fix wording in RegEx description

src/watchers.rst
A plugin for tmux that allows monitoring activity in sessions and panes wit AW
=> docs: adding akohlbecker/aw-watcher-tmux to watchers

src/watchers.rst
Removes the (my) duplicate Sublime Text plugin added in #59.
kostasdizas/aw-watcher-sublime should be considered the one true ST watcher, and has been updated to be functionally equivalent to what I had rewritten. Plus, their's is the one in package control and ST seems to really try to minimize multiple similar packages, for good reason.
=> docs: remove duplicate Sublime Text watcher

src/examples/query_client.py, src/examples/querying-data.rst, src/examples/writing-watchers.rst, src/getting-started.rst
I wanted to do a little project using data from ActivityWatch, and noticed that the examples regarding _aw-client_ are incomplete or outdated. 
For now, I only added a note with a link to the _aw-client_ repo, because it wasn't immediately obvious that _aw-client_ would need to be manually installed. (At least that's what I assumed, because for me, it doesn't work without.)
But there are other problems like strings instead of datetimes being passed to `client.query`, which leads to errors.
Also, it should be emphasized that in the example, _aw-client_ tries to connect to a testing instance (if I understood that correctly).
Since I'm only just getting into it, I'm not sure if I am the right person to edit the documentation, but I thought I'd give it a try.
---
I found some unrelated typos …
=> docs: improvements to aw-client example

src/features/exporting-data.rst
I'm happy to reword this if there are any preferences to use curl or requests instead.
=> Docs: exporting data

src/getting-started.rst
I just setup the ActivityWatch on MacOS and I ran into the other issues outlined in #334.  I want to update the note to try to make it more clear that a new user still needs to work around this issue, bc Catalina was old when I checked the documentation I figured this was already taken care of and didn't get re-directed to the issue until some more google searching.
Lmk if you would prefer a writeup of [the steps](https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-1052392579) @may posted.
=> docs(macos): add more detail to the macOS install instructions

src/examples/querying-data.rst
The old example causes `There's no bucket named 'window_bucket'` error.
I updated it with default query in [aw-webui](https://github.com/ActivityWatch/aw-webui/blob/fb331628c8f0f52b36ac9720148624bab8a4d2d3/src/views/QueryExplorer.vue#L47-L51)
=> docs: update query example combining AFK

src/examples/minimal_client.py
Executing the `minimal_client.py` example will result in an unhandled exception being thrown.
```
bucket_id = f"test-client-bucket_{client.hostname}"
AttributeError: 'ActivityWatchClient' object has no attribute 'hostname'
```
This adds the [correct attribute name](https://github.com/ActivityWatch/aw-client/blob/df8776c59000bb785542bd4fe4c37ff61f975420/aw_client/client.py#L76) for the client's hostname.
=> Fix ActivityWatchClient AttributeError

src/watchers.rst
See ActivityWatch/aw-watcher-afk#55
=> docs: document 3-min default timeout for `aw-watcher-afk`

src/configuration.rst
see ActivityWatch/aw-watcher-afk#55
=> docs: better document aw-watcher-afk `timeout` config, link to defaults in source

src/watchers.rst
I've written a simple Anki add-on to track time spent reviewing flashcards: https://github.com/abdnh/aw-watcher-anki
=> docs(watchers): add aw-watcher-anki

src/watchers.rst
Wrote [an AW watcher for mpv](https://github.com/RundownRhino/aw-watcher-mpv-sender). Early version (no visualizations, etc), but I've been using it for a few days and what's implemented so far seems to be working fine.
=> docs(watchers): add aw-watcher-mpv

src/watchers.rst
aw-watcher-obsidian is a watcher capable of watching files in the obsidian markdown editor. The watcher is tested under Linux, it might work under windoes/Mac too but i don not have any options to test those.
This is an early version, issues may arise.
The obsidian plugin is open source at https://github.com/LordGrimmauld/aw-watcher-obsidian
=> docs(watchers): Add reference to aw-watcher-obsidian

src/watchers.rst
Many Chrome extensions will work with Microsoft Edge as it is based on Google Chrome.  This extension has been loaded into the current version of Edge and shows results in ActivityWatch.
=> Update watchers.rst to include support for Edge browser

src/running-on-gnome.rst
The script was causing both watchers to crash due to termination of start.sh. See (https://github.com/ActivityWatch/activitywatch/issues/938).
=> fix: error in start.sh script

src/getting-started.rst
I added autostart instructions for Ubuntu and the instructions are shown in tabs now, just like the installation instructions.
Was thinking about adding screenshots, but it would bloat the tab I think.
I like how it looks now.
Love your product! :heart: 
Cheers
=> Add autostart instructions for Ubuntu

src/directories.rst
Directory typo fix
Directory with typo: ~/Library/Application Support/activitywatch
Directory fix: ~/Library/Application\ Support/activitywatch
Closes #127
=> MacOS data directory typo

src/running-on-gnome.rst
It is needed to place quotes around the filepath because '\~' is used and the desktop file is invalid if '\~' is used outside of quotes. I hope it prevents someone else from running into the same problem.
=> Add quotes to filepaths in GNOME desktop files suggestion

src/watchers.rst
Per [X11+Wayland+KDE+Gnome watcher on Rust](https://github.com/orgs/ActivityWatch/discussions/874)
=> Add awatcher to watchers list

src/getting-started.rst
Currently, when viewing the [Getting Started](https://docs.activitywatch.net/en/latest/getting-started.html) instructions it instructs to download the latest release from github, but links to all releases. This includes pre-release versions which are probably not suitable for people looking at the getting started guide. This PR links directly to the latest release.
=> docs: directly link to latest release

src/watchers.rst
[Toggl](https://toggl.com/) is a time-tracking service. It is useful to use this tracking if you are away from your computer or if you have mixed tasks that you work on.
=> Docs(watchers): Add aw-watcher-toggl

src/watchers.rst
This covers most media players. I based the idea and format on aw-watcher-spotify, but I wanted to support any player, fortunately there is a way.
=> Add aw-watcher-media-player to watchers

src/faq.rst, src/watchers.rst
FAQ suggests that it's impossible while it's not completely true.
Also, https://github.com/flexagoon/aw-watcher-gnome is deprecated.
=> Fix pessimistic FAQ about Wayland
