ActivityWatch/docs

examples/minimal_client.py
Adds missing parenthesis in the example
=> Add missing parenthesis in docs

getting-started.rst
I have been using ActivityWatch for a while and wanted to contribute, so I thought this would be a good place to start! Let me know if you'd like me to make any changes to what I have here.
This addresses issue 141 in the main repo: https://github.com/ActivityWatch/activitywatch/issues/141
=> Added config file information

installing-from-source.rst
https://github.com/ActivityWatch/activitywatch/issues/176#issuecomment-375265938
=> Add link to .desktop file issue 

installing-from-source.rst
Needed to package it to have distributable files and run them at startup
=> How to package activitywatch

watchers.rst
Hi, 
I just develop an Activity Watcher plugin, I just add a link to the watcher.
cya.
=> Add JetBrains IntelliJ plugin

watchers.rst
Fix generation of https://activitywatch.readthedocs.io/en/latest/watchers.html#editor-watchers 
space missing
=> Fix generation

watchers.rst
I created a simple watcher for Sublime Text 3
=> Added watcher for Sublime Text 3

src/watchers.rst
I can proudly to announce that my custom Activity Watch watcher which monitors my height-adjustable table is finally finished.
https://github.com/Alwinator/aw-watcher-table
=> Add my new aw-watcher-table to the documentation

src/examples/client.py
Fixes https://github.com/ActivityWatch/activitywatch/issues/564
=> examples: Fix broken example reference client

src/directories.rst, src/index.rst, src/remote-server.rst
Got fed up with answering the same question over and over, this should settle it once and for all...
=> docs: added 'Remote server' page

src/installing-from-source.rst
Adds a bit more clarity for the next dev to read through the docs.
=> Note about why a global venv is preferred to poetry-managed environments

src/architecture.rst, src/buckets-and-events.rst, src/installing-from-source.rst, src/security.rst
Added the --version on checking if the commands are working if the shortcut -v does not work for users. (E.g git -v for me).
=> docs: misc changes

src/watchers.rst
I hope you like it. Maybe it is also useful for you.
=> Add my new aw-watcher-utilization to the docs

src/faq.rst
Should at least somewhat clarify that activitywatch data cannot be used as "proof of work" (not in terms of crypto though lol).
https://forum.activitywatch.net/t/please-explain-i-have-a-serious-issue/1634/2
=> docs: Add statement about accuracy to the FAQ

src/installing-from-source.rst, src/watchers.rst
- Note about URL extracted via window watcher
- Note about how to update all submodules
=> submodule update and watcher help

src/features/filtering-data.rst
The script name changed. Also for me it was easier to open the database itself.
=> docs: update how to delete data

src/faq.rst
Fixed grammatical mistakes and improved the readability of some text.
=> docs: minor grammatical changes

src/watchers.rst
Hi,
Just an update of information for jetbrains watcher.
=> Update Jetbrains watcher informations

src/introduction.rst
Hey :wave:,
This PR will fix :
1 typo in `src/introduction.rst`
Best!
=> docs: fix typos

src/watchers.rst
`aw-watcher-netstatus` monitors if you're connected to a network.
**Test Plan:**
```
$ poetry install
$ poetry run make
$ python3 -m http.server 3003 --directory _build/html
```
=> docs(watchers): Add aw-watcher-netstatus watcher
